networks:
  doofinder_net:
    external: true
services:
  search:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: doofinder/cluster
    expose:
      - "9200"
      - "9300"
    ports:
      - "9205:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      ES_JAVA_OPTS:   "-Xms512m -Xmx512m"
      node.master:    "true"
      node.data:      "true"
      node.ingest:    "false"
      node.attr.type: "search"
      node.name:      "search"
    networks:
      doofinder_net:
        aliases:
          - cluster
          - search
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - search:/usr/share/elasticsearch/data
  index:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: doofinder/cluster
    expose:
      - "9200"
      - "9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      ES_JAVA_OPTS:   "-Xms512m -Xmx512m"
      node.master:    "false"
      node.data:      "true"
      node.ingest:    "true"
      node.attr.type: "index"
      node.name:      "index"
    networks:
      doofinder_net:
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - index:/usr/share/elasticsearch/data
version: '2.2'
volumes:
  search:
  index:
